CREATE DATABASE todo_app;

\c todo_app

CREATE TABLE IF NOT EXISTS tasks(
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	description TEXT,
	completed BOOLEAN DEFAULT FALSE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);